version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./backend/database.sqlite:/app/database.sqlite
    environment:
      - EMAIL=${EMAIL}
      - PASS=${PASS}
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
