services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - backend-data:/app/data
      - ./backend/uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - EMAIL=${EMAIL}
      - PASS=${PASS}
      - SESSION_SECRET=${SESSION_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8080}
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend-data:
